# Generated by Django 5.2.4 on 2026-03-22 16:44

import core.models
import datetime
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prato", models.CharField(max_length=150, verbose_name="Prato")),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                ("calorias", models.IntegerField(verbose_name="Calorias")),
                ("peso", models.IntegerField(verbose_name="Peso")),
                (
                    "tamanho_prato",
                    models.CharField(
                        choices=[
                            ("pequeno", "Pequeno"),
                            ("médio", "Médio"),
                            ("grande", "Grande"),
                        ],
                        max_length=20,
                        verbose_name="Tamanho do prato",
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Imc"
                    ),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alimento",
                "verbose_name_plural": "Alimentos",
            },
        ),
        migrations.CreateModel(
            name="Aquecimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("link", models.CharField(max_length=400, verbose_name="Link")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 720, "width": 1280}
                        },
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aquecimento",
                "verbose_name_plural": "Aquecimentos",
            },
        ),
        migrations.CreateModel(
            name="Contatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(max_length=50, verbose_name="Endereço")),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="BR", verbose_name="Telefone"
                    ),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="E-mail")),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
        migrations.CreateModel(
            name="Exercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=40, verbose_name="Nome")),
                ("objetivo", models.CharField(max_length=80, verbose_name="Objetivo")),
                (
                    "repeticoes_ou_tempo",
                    models.CharField(max_length=10, verbose_name="Repetições/Tempo"),
                ),
                (
                    "pausa",
                    models.DurationField(
                        default=datetime.timedelta(seconds=90),
                        verbose_name="Pausa (min/s)",
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Imc"
                    ),
                ),
                (
                    "praticante",
                    models.CharField(
                        choices=[
                            ("sedentário", "Sedentário"),
                            ("regular", "Regular"),
                            ("praticante", "Praticante"),
                        ],
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "tipo_corporal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ectomorfo", "Ectomorfo"),
                            ("mesomorfo", "Mesomorfo"),
                            ("endomorfo", "Endomorfo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo do corpo",
                    ),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercício",
                "verbose_name_plural": "Exercícios",
            },
        ),
        migrations.CreateModel(
            name="Objetivos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=20, verbose_name="Título")),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 506, "width": 362}
                        },
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objetivo",
                "verbose_name_plural": "Objetivos",
            },
        ),
        migrations.CreateModel(
            name="RedesSociais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rede_social",
                    models.CharField(max_length=200, verbose_name="Rede social"),
                ),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("fa fa-pinterest", "Pinterest"),
                            ("fa fa-facebook", "Facebook"),
                            ("fa fa-instagram", "Instagram"),
                            ("fa fa-dribbble", "Dribbble"),
                            ("fa fa-behance", "Behance"),
                            ("fa fa-youtube", "Youtube"),
                        ],
                        max_length=50,
                        verbose_name="Tamanho do prato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rede social",
                "verbose_name_plural": "Redes sociais",
            },
        ),
        migrations.CreateModel(
            name="Servicos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=20, verbose_name="Título")),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={"thumb": {"crop": True, "height": 82, "width": 82}},
                        verbose_name="Imagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.CreateModel(
            name="TiposTreinos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treino", models.CharField(max_length=20, verbose_name="Treino")),
                (
                    "repeticoes_ou_tempo_min",
                    models.CharField(
                        max_length=20, verbose_name="Rep. ou tempo mínimo"
                    ),
                ),
                (
                    "repeticoes_ou_tempo_max",
                    models.CharField(
                        max_length=20, verbose_name="Rep. ou tempo máximo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de treino",
                "verbose_name_plural": "Tipos de treinos",
            },
        ),
        migrations.CreateModel(
            name="Visitantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=40, verbose_name="Título")),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="Descrição"),
                ),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "icone",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to=core.models.get_file_path,
                        variations={
                            "thumb": {"crop": True, "height": 480, "width": 480}
                        },
                        verbose_name="Ícone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitante",
                "verbose_name_plural": "Visitantes",
            },
        ),
        migrations.CreateModel(
            name="CustomUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("data_nascimento", models.DateField(verbose_name="Nascimento")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Membro da equipe"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
            managers=[
                ("objects", core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name="BiotipoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(2.5),
                        ],
                        verbose_name="Altura (m)",
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Peso (kg)"
                    ),
                ),
                (
                    "tipo_corporal",
                    models.CharField(
                        choices=[
                            ("ectomorfo", "Ectomorfo"),
                            ("mesomorfo", "Mesomorfo"),
                            ("endomorfo", "Endomorfo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo do corpo",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("sedentário", "Sedentário"),
                            ("regular", "Regular"),
                            ("praticante", "Praticante"),
                        ],
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Biotipo",
                "verbose_name_plural": "Biotipos",
            },
        ),
        migrations.CreateModel(
            name="Localizacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=500, verbose_name="Localização")),
                (
                    "contato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.contatos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Localizacao",
                "verbose_name_plural": "Localizacoes",
            },
        ),
    ]
